branch-defaults:
  master:
    environment: WebServer
global:
  application_name: ClusteringMadness
  default_ec2_keyname: ClusteringMadness
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
