branch-defaults:
  default:
    environment: Worker
  master:
    environment: null
global:
  application_name: ClusteringMadness
  default_ec2_keyname: ClusteringMadness
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: null
