branch-defaults:
  master:
    environment: WebServer
    group_suffix: null
global:
  application_name: ClusteringMadness
  default_ec2_keyname: ClusteringMadness
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
